---
apiVersion: v1
kind: Service
metadata:
  name: github-workflow
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: github-workflow
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      name: workflow
  selector:
    app: github-workflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-workflow
  template:
    metadata:
      labels:
        app: github-workflow
    spec:
      containers:
        - name: worker
          image: rachfop/github-workflow-worker:v1.0
          imagePullPolicy: Always
          env:
            - name: TEMPORAL_HOST_URL
              value: im-the-admin-now.a2dd6.cloud:7233
            - name: TEMPORAL_NAMESPACE
              value: im-the-admin-now.a2dd6
            - name: TEMPORAL_MTLS_TLS_CERT
              value: /etc/certs/tls.crt
            - name: TEMPORAL_MTLS_TLS_KEY
              value: /etc/certs/tls.key
          volumeMounts:
            - mountPath: /etc/certs
              name: certs
        - name: workflow
          image: rachfop/github-workflow:v1.0
          imagePullPolicy: Always
          ports:
            - name: workflow
              containerPort: 5000
          env:
            - name: TEMPORAL_HOST_URL
              value: im-the-admin-now.a2dd6.cloud:7233
            - name: TEMPORAL_NAMESPACE
              value: im-the-admin-now.a2dd6
            - name: TEMPORAL_MTLS_TLS_CERT
              value: /etc/certs/tls.crt
            - name: TEMPORAL_MTLS_TLS_KEY
              value: /etc/certs/tls.key
          volumeMounts:
            - mountPath: /etc/certs
              name: certs
      volumes:
        - name: certs
          secret:
            defaultMode: 420
            secretName: github-workflow-tls-secret
